# McConway KJ, Jones MC, Taylor PC.
# Statistical Modelling using GENSTAT.
# London, UK: Arnold, 1999.
# ISBN: 0340759852

# Code fragment for model selection
print(model)
anova(model, update(model, .~ 1), test = 'Chisq')
summary(model)
drop1(model, test = 'Chisq')
model <- step(model, direction = 'both') # from full model, bad practice

# Code fragment for diagnostic plots
par(mfrow = c(2, 3))
plot(model, which = 1:6)
dev.off()

# Chapter 10: What are generalised linear models?
crashes <- read.table('crashes.dat', header = TRUE)
plot(crashes ~ cover, crashes, pch = 4)
crashes$lcover <- log(crashes$cover + .5)
plot(crashes ~ lcover, crashes, pch = 4)
model <- glm(crashes ~ lcover, crashes, family = 'poisson')
x <- seq(-1, 6, by = .1)
y <- predict(model, newdata = data.frame(lcover = x), type = 'response')
points(y ~ x, type = 'l')

ship1907 <- read.table('ship1907.dat', header = TRUE)
plot(crew ~ tonnage, ship1907, pch = c(20, 4)[power])
legend('topleft', bty = 'n', pch = c(4, 20), legend = c('steam', 'sail'))
model <- glm(crew ~ tonnage + power, ship1907, family = 'poisson')
x <- expand.grid(tonnage = seq(20, 3500, by = 100), power = levels(ship1907$power))
x$hat <- predict(model, newdata = data.frame(x), type = 'response')
points(hat ~ tonnage, x[x$power == 'steam', ], type = 'l', lty = 'dashed')
points(hat ~ tonnage, x[x$power == 'sail', ], type = 'l')
model <- glm(crew ~ log(tonnage) + power, ship1907, family = 'poisson')
model <- update(model, .~. - power)
x$hat <- predict(model, newdata = data.frame(x), type = 'response')
plot(crew ~ log(tonnage), ship1907, pch = c(20, 4)[power])
points(hat ~ log(tonnage), x[x$power == 'steam', ], type = 'l', lty = 'dashed')
points(hat ~ log(tonnage), x[x$power == 'sail', ], type = 'l')

insect <- read.table('insect.dat', header = TRUE)
insect <- transform(insect, prop = ndead / nins, nlive = nins - ndead)
insect$mix <- factor(insect$mix, levels = c('B', levels(insect$mix)[2:4], 'A'))
plot(prop ~ log(dose), insect, pch = c(4, 1, 3, 20, 0)[mix])
legend('topleft', bty = 'n', pch = c(4, 1, 3, 20, 0), legend = levels(insect$mix))
model <- glm(as.matrix(insect[, c('ndead', 'nlive')]) ~ log(dose) + mix, insect, family = 'binomial')
print(x <- data.frame(model.matrix(model)))
colnames(x)[2:6] <- c('ldose', 'm13', 'm22', 'm31', 'ma')
model <- update(model, .~ x$ldose + x$m13 + x$m22 + x$m31 + x$ma)
model1 <- update(model, .~ x$ldose + x$m13 + x$m22 + x$m31)
model2 <- update(model, .~ x$ldose + x$m22 + I(x$m13 + x$m31))
model3 <- update(model, .~ x$ldose + I(x$m22 + x$m13 + x$m31))
anova(model, model1, test = 'Chisq')
anova(model1, model2, test = 'Chisq')
anova(model2, model3, test = 'Chisq')
rm(model, model1, model2, model3)

toxo <- read.table('toxo.dat', header = TRUE)
toxo <- transform(toxo, prop = npos / ntest, nneg = ntest - npos, group = as.numeric(ntest >= 30) + 1)
plot(prop ~ rain, toxo, pch = c(4, 20)[group])
legend('topright', bty = 'n', pch = c(4, 20), legend = c('ntest < 30', 'ntest >= 30'))
model <- glm(as.matrix(toxo[, c('npos', 'nneg')]) ~ rain, toxo, family = 'binomial')
model <- update(model, .~ poly(rain, 3))
x <- seq(1.6, 2.3, by = .01)
y <- predict(model, newdata = data.frame(rain = x), type = 'response')
model <- update(model, .~ rain + I(rain^2) + I(rain^3) + I(rain^4))
anova(model, test = 'Chisq')
plot(prop ~ rain, toxo, pch = 4)
points(y ~ x, type = 'l')

leuksurv <- read.table('leuksurv.dat', header = TRUE)
par(mfrow = c(1, 2))
plot(time ~ wbc, leuksurv, pch = c(4, 20)[ag])
legend('topright', bty = 'n', cex = .8, pch = c(20, 4), legend = paste('ag = ', c('positive', 'negative')))
plot(time ~ log(wbc), leuksurv, pch = c(4, 20)[ag])
model <- glm(time ~ ag * log(wbc), leuksurv, family = 'Gamma')
model <- update(model, .~ ag + log(wbc))
x <- expand.grid(wbc = seq(750, 10^5, by = 100), ag = levels(leuksurv$ag))
x$hat <- predict(model, newdata = x, type = 'response')
par(mfrow = c(1, 1))
plot(time ~ log(wbc), leuksurv, pch = c(4, 20)[ag], ylim = c(0, 250), xlim = c(6, 12))
points(hat ~ log(wbc), x[x$ag == 'pos', ], type = 'l')
points(hat ~ log(wbc), x[x$ag == 'neg', ], type = 'l', lty = 'dashed')

hardness <- read.table('hardness.dat', header = TRUE)
model <- glm(hardness ~ density, hardness, family = Gamma('identity'))
x <- 20:70
y <- predict(model, newdata = data.frame(density = x), type = 'response')
plot(hardness ~ density, hardness, pch = 4)
points(y ~ x, type = 'l')
model <- update(model, .~. + I(1/density))
drop1(model, test = 'F')
y <- predict(model, newdata = data.frame(density = x), type = 'response')
model <- lm(log(hardness) ~ log(density), hardness)
y0 <- exp(predict(model, newdata = data.frame(density = x)))
plot(hardness ~ density, hardness, pch = 4)
points(y ~ x, type = 'l')
points(y0 ~ x, type = 'l', lty = 'dashed')
